### ISSUE TITLE
http: prefix is always added

### ISSUE THREAD

**Issue by maikheinrich** [evcc-io/app#10]
Hi Michael,

when I added a url manually and enter "http://evcc'" your app is using "http://http://evcc"
We must enter it without http:// prefix. But in the field example is "http://evcc:7070"
So most users try it with http://. But as of now, this is not working
Please check if the input begin with http:// and when yes, we need no prefix.
 

Thank You

Maik

**Comment by naltatis** [comment]
Can you describe step by step what you're doing to get this effect? `http://` should only be added when entering a url without http(s) protocol. See here: https://github.com/evcc-io/app/blob/main/utils/server.js#L3-L12

**Comment by maikheinrich** [comment]
Hi Michael,

I couldn't reproduce it again. I probably typed http:/evcc.
The problem was clearly with the keyboard. Sorry for the circumstances
