### ISSUE TITLE
Absturz bei autom. Suche im Netzwerk und manchmal bei "Server ändern".

### ISSUE THREAD

**Issue by ben-germany** [evcc-io/app#14]
direkt beim ersten Start bei der autom. Suche nach EVCC Server ist die app abgestürzt. Beim erneuten Start und manueller Eingabe funktioniert sie. Vereinzelt (aber nicht immer reproduzierbarere ) Absturz bei "Server ändern".
(iPhone 13 Pro mit iOS 17.5.1., EVCCv0.127.2 via docker auf Synology-NAS.

Generell läuft die APP bisher recht gut.

**Comment by naltatis** [comment]
@ben-germany kannst du verifizieren ob das bei dir noch ein Thema ist? Ich konnte es bislang nicht reproduzieren.

**Comment by ben-germany** [comment]
Ich habe das Problem schon länger nicht mehr. Derzeit läuft die App stabil.

**Comment by naltatis** [comment]
Danke für die Rückmeldung. Dann mach ich hier erst einmal zu.
