### ISSUE TITLE
Release Android version

### ISSUE THREAD

**Issue by naltatis** [evcc-io/app#4]

**Comment by tobiasKaminsky** [comment]
I have quite a bit experience with Android.
What is the goal? 
Adding it first to Fdroid? 
For Gplay a real dev account is needed, so I suggest to go first with Fdroid.

**Comment by typxxi** [comment]
I like to have an android version too so I gave it a star/subscribed.
But of cause I have not installed nor used it cause no iphone nor ipad here available.

**Comment by r1st0** [comment]
I compiled the apk from this repo and it is working. Still would be nice to see an official apk in the releases here.

**Comment by r1st0** [comment]
> > I compiled the apk from this repo and it is working. Still would be nice to see an official apk in the releases here.
> 
> Hello, it is possible to share this compiled apk?

I dont know if it is allowed to share binaries here, but lets try.
It is compiled for ARMv9. I dont know if this matters, but it can be a reason if things are not working.
https://upload.adminforge.de/r/dsxSazm0jH#LAhGtIYrHHzXgjfOeAQOetr+COQtRM6kRP5kz6/RF0Y=

**Comment by Madmax2341** [comment]
Thx, works fine :-)

**Comment by ravagerxxx** [comment]
No clue how to build it, could you elaborate or create another apk?

**Comment by naltatis** [comment]
We haven't gotten around to android testing to the extend I want to. But I'll publish a prelease here soon.

**Comment by ravagerxxx** [comment]
was trying to run evcc in a webview apk myself but for some odd reason there is always only a blank screen in the webview

**Comment by r1st0** [comment]
> We haven't gotten around to android testing to the extend I want to. But I'll publish a prelease here soon.

I did not test extensively, but used my own compiled version now over a month and had no issues so far.
A minor: there is a white top bar in dark mode.
And: pull-to-refresh would be nice.

**Comment by ravagerxxx** [comment]
Mind Posting a APK again?

> > We haven't gotten around to android testing to the extend I want to. But I'll publish a prelease here soon.
> 
> I did not test extensively, but used my own compiled version now over a month and had no issues so far. A minor: there is a white top bar in dark mode. And: pull-to-refresh would be nice.

Mind Posting your APK again ?

**Comment by naltatis** [comment]
I've published a prerelease build. Feel free to provide feedback and bug reports as separate new issues.
