### ISSUE TITLE
Kontextmenü nicht in Systemsprache

### ISSUE THREAD

**Issue by naltatis** [evcc-io/app#9]
![Bildschirmfoto 2024-03-04 um 11 11 32](https://github.com/evcc-io/app/assets/152287/d70a4524-fa18-41c1-a82c-f2f2d038cc2c)

**Comment by Maschga** [comment]
Auf Android kann ich diesen Bug nicht reproduzieren.

**Comment by naltatis** [comment]
Ich konnte den damals reproduzieren, hab aber in React native keine direkt möglichkeit befunden das zu ändern. daher wüd ich den erst einmal schließen.
